### ISSUE TITLE
Feature: on-screen display of current settings

### ISSUE THREAD

**Issue by bazmonk** [bazmonk/digigurdy-baz#17]
I mentioned this in another issue, but just to give it a spot...

Per-request, list the current tuning/setting being used on-screen during play.

This should be easy to include in the step that displays the on-screen note being played.

Since we will be using part of the display, I don't know yet if I can display a bitmap on part of the screen along with text.  I think I'll have to either:

- re-do all the bitmaps to fit in a smaller area (truth be told... I probably won't do this on my own, but I'll look into it if someone else wants to make the bitmaps)
- Settle for all-text on the display during play.

**Comment by bazmonk** [comment]
I'm putting this with the initial re-write milestone: I'll add this in when I write the actual display portions.

**Comment by bazmonk** [comment]
I tweaked the format a bit more, I like it now.

One issue is the sharps/flats.  Formatting it to accommodate "G4" or "G4#" is ok.  Formatting it to make "G4" or "G4#/A4b" look nice is more difficult because text space is limited.  I can squeeze it in but the display gets rather busy that way.  I'll probably do it anyway because I think folks will want it more than they'll dislike how busy the display gets.  We all gotta make sacrifices, lol.

**Comment by Gubbledenut** [comment]
The note is G or G# the midi qualifier is the number, which in note display isn't that beneficial , but if you must put the number I suggest G4 and G#4, more useful is to include the DoReMi format either as an option or as an addition but leave the midi octave qualifier out??? however dod keep it in the tuning menus..I am happy to edit that array

**Comment by bazmonk** [comment]
> I suggest G4 and G#4

Do you mean as opposed to G4 and G4#?

I will eventually implement the DoReMi functionality eventually.

**Comment by bazmonk** [comment]
@Gubbledenut In the DoReMi version, do you want octaves represented at all?  E.g. C4 = Do, is C3 also "Do", or is there a way to signify the octave?

I'm not familiar with how that system is used to refer to a specific note, or if it is at all.

**Comment by Gubbledenut** [comment]
Yes the octaves ate the same. I will put an array/list together with the ABC and the DoReMi conventions

**Comment by Gubbledenut** [comment]
Yes the octave should be the last statement as on G#4 not G4#

**Comment by bazmonk** [comment]
Ok, fixed the G#4 vs G4# thing.

**Comment by bazmonk** [comment]
I'm closing this issue.  On-screen display during play has been implemented.  Bitmaps I've already determined will come after v1.0.  DoReMi is being addressed in a different issue.
