### ISSUE TITLE
option 1 not working on note selection screen

### ISSUE THREAD

**Issue by Gubbledenut** [bazmonk/digigurdy-baz#63]
I selected option 2  Big note on the Playing screen, 
It now won't let me select option 1 Big note and Staff
It seems just to be button one wrong there, everywhere else button one works.
Ver 1.2.6

**Comment by Gubbledenut** [comment]
found it 
line 1724 if (myOkButton->wasPressed()) {
should be if (my1Button->wasPressed()) {

**Comment by bazmonk** [comment]
Fixed, thanks again.
