### ISSUE TITLE
Bounce looks deprecrated (see Bounce2)

### ISSUE THREAD

**Issue by SalusaSecondus** [bazmonk/digigurdy-baz#77]
I'm trying to set up my build environment and the Bounce library looks deprecated in favor of [Bounce2](https://github.com/thomasfredericks/Bounce2). We should upgrade. (I cannot even find `Bounce` listed in the library manager anymore.)

**Comment by SalusaSecondus** [comment]
Stupid mistake on my part getting set up. Closing this.

**Comment by bazmonk** [comment]
No worries… I do think Bounce is deprecated or going that way soon, so moving to Bounce2 might be in the cards…
