### ISSUE TITLE
Support Program Change to indicate saved tunings

### ISSUE THREAD

**Issue by SalusaSecondus** [bazmonk/digigurdy-baz#79]
As bs-16i supports changing scenes based on a Program Change message sent via midi, I would like to have changing the saved tuning on my gurdy automatically change the scene in bs-16i.

This would be a new top-level option (saved to the EEPROM). When set, the index of the saved tuning (probably 0-3 for presets 1-4 and 4-7 for user slots 1-4) would be sent along midi channel 1 as a program control message.

(My intention is to write this feature myself, but I'm cutting an issue to track the request and let people comment on it.)

**Comment by bazmonk** [comment]
Sounds good!

Please start with byte 101 in the EEPROM so it jives with the other
settings in there.

-Basil

**Comment by bazmonk** [comment]
@SalusaSecondus Finally looking at this, sorry for the delay...

**Comment by bazmonk** [comment]
I'm closing this issue now that the merge is in as of version 1.4.1.
